core_bundle:
    resource: "@PmsCoreBundle/Resources/config/routing.yml"
    prefix:   /

Pms_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
