<?php

namespace Pms\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRequisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRequisitionRepository extends EntityRepository
{
}
