homepage:
    pattern: /
    defaults: { _controller: UserBundle:Default:index }

user_list:
    pattern: /user/list
    defaults: { _controller: UserBundle:User:index }

user_add:
    pattern: /user/add
    defaults: { _controller: UserBundle:User:userAdd }

user_update:
    pattern: /user/update/{id}
    defaults: { _controller: UserBundle:User:userUpdate }
    requirements:
          id: \d+

user_active:
    pattern: /user/active/{id}
    defaults: { _controller: UserBundle:User:userActive }
    requirements:
          id: \d+

user_deactivated:
    pattern: /user/deactivated
    defaults: { _controller: UserBundle:User:userDeactivated }

user_deactivate:
    pattern: /user/deactivate/{id}
    defaults: { _controller: UserBundle:User:userDeactivate }
    requirements:
          id: \d+

user_delete:
    pattern: /user/delete/{id}
    defaults: { _controller: UserBundle:User:userDelete }
    requirements:
          id: \d+

user_deleted:
    pattern: /user/deleted
    defaults: { _controller: UserBundle:User:userDeleted }

user_archive:
    pattern: /user/archive/{id}
    defaults: { _controller: UserBundle:User:userArchive }
    requirements:
          id: \d+

user_view:
    pattern: /user/view/{id}
    defaults: { _controller: UserBundle:User:userView }
    requirements:
          id: \d+

username_check:
    pattern: /username/check
    defaults: { _controller: UserBundle:User:usernameCheck }
    options:
            expose: true

email_check:
    pattern: /email/check
    defaults: { _controller: UserBundle:User:emailCheck }
    options:
            expose: true

fos_user_security:
     resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
     prefix: /profile

fos_user_register:
     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
     prefix: /register

fos_user_resetting:
     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
     prefix: /resetting

fos_user_change_password:
     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
     prefix: /profile



