receive_add:
    pattern: /receive/item
    defaults: { _controller: PmsCoreBundle:Core:receiveAdd }

receive_add_new:
    pattern: /receive/item/new
    defaults: { _controller: PmsCoreBundle:Core:receiveNew }

receive_save:
    pattern: /receive/save
    defaults: { _controller: PmsCoreBundle:Core:receiveSave }

upload_add:
    pattern: /upload/file
    defaults: { _controller: PmsCoreBundle:Core:uploadAdd }

vendor_add:
    pattern: /vendor
    defaults: { _controller: PmsCoreBundle:Vendor:vendorAdd }

vendor_list:
    pattern: /vendor/list
    defaults: { _controller: PmsCoreBundle:Vendor:vendorList }

vendor_ajax_add:
    pattern: /vendor/add
    defaults: { _controller: PmsCoreBundle:Vendor:vendorAjaxAdd }
    options:
            expose: true

vendor_check:
    pattern: /vendor/check
    defaults: { _controller: PmsCoreBundle:Vendor:vendorCheck }
    options:
            expose: true

vendor_deleted:
    pattern: /vendor/deleted
    defaults: { _controller: PmsCoreBundle:Vendor:vendorDeleted }

vendor_deleted_list:
    pattern: /vendor/deleted/list
    defaults: { _controller: PmsCoreBundle:Vendor:vendorDeletedList }

vendor_delete:
    pattern: /vendor/delete/{id}
    defaults: { _controller: PmsCoreBundle:Vendor:vendorDelete }
    requirements:
          id: \d+

vendor_active:
    pattern: /vendor/active/{id}
    defaults: { _controller: PmsCoreBundle:Vendor:vendorActive }
    requirements:
          id: \d+

vendor_update:
    pattern: /vendor/update/{id}
    defaults: { _controller: PmsCoreBundle:Vendor:vendorUpdate }
    requirements:
          id:  \d+

purchase_order_add:
    pattern: /purchase/order
    defaults: { _controller: PmsCoreBundle:PurchaseOrder:purchaseOrderAdd }

purchase_order_new:
    pattern: /purchase/order/new
    defaults: { _controller: PmsCoreBundle:PurchaseOrder:purchaseOrderNew }

purchase_order_new_save:
    pattern: /purchase/order/new/save
    defaults: { _controller: PmsCoreBundle:PurchaseOrder:purchaseOrderSave }

purchase_order_details:
    pattern: /purchase/order/details/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseOrder:purchaseOrderDetails }

purchase_order_total_quantity:
    pattern: /purchase/total/quantity
    defaults: { _controller: PmsCoreBundle:PurchaseOrder:purchaseOrderTotalQuantity }
    options:
            expose: true

purchase_requisition_add:
    pattern: /purchase/requisition
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionAdd }

purchase_requisition_closed:
    pattern: /purchase/requisition/closed
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionClosed }

purchase_requisition_open:
    pattern: /purchase/requisition/open
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionOpen }

purchase_requisition_new:
    pattern: /purchase/requisition/new
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionNew }

purchase_requisition_edit:
    pattern: /purchase/requisition/edit/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionEdit }
    requirements:
          id: \d+

purchase_requisition_claim:
    pattern: /purchase/requisition/item/claim/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionClaim }
    requirements:
          id: \d+

purchase_requisition_close:
    pattern: /purchase/requisition/item/close/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionClose }
    requirements:
          id: \d+

purchase_requisition_details:
    pattern: /purchase/requisition/details/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionDetails }

purchase_requisition_approve_project_head:
    pattern: /purchase/requisition/approve/projectHead/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionApproveByProjectHead }
    requirements:
          id: \d+

purchase_requisition_approve_category_head_one:
    pattern: /purchase/requisition/approve/CategoryHeadOne/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionApproveByCategoryHeadOne }
    requirements:
          id: \d+

purchase_requisition_approve_category_head_two:
    pattern: /purchase/requisition/approve/CategoryHeadTwo/{id}
    defaults: { _controller: PmsCoreBundle:PurchaseRequisition:purchaseRequisitionApproveByCategoryHeadTwo }
    requirements:
          id: \d+

buyer_add:
    pattern: /buyer
    defaults: { _controller: PmsCoreBundle:Buyer:buyerAdd }

buyer_list:
    pattern: /buyer/list
    defaults: { _controller: PmsCoreBundle:Buyer:buyerList }

buyer_ajax_add:
    pattern: /buyer/add
    defaults: { _controller: PmsCoreBundle:Buyer:buyerAjaxAdd }
    options:
            expose: true

buyer_check:
    pattern: /buyer/check
    defaults: { _controller: PmsCoreBundle:Buyer:buyerCheck }
    options:
            expose: true

buyer_deleted:
    pattern: /buyer/deleted
    defaults: { _controller: PmsCoreBundle:Buyer:buyerDeleted }

buyer_deleted_list:
    pattern: /buyer/deleted/list
    defaults: { _controller: PmsCoreBundle:Buyer:buyerDeletedList }

buyer_delete:
    pattern: /buyer/delete/{id}
    defaults: { _controller: PmsCoreBundle:Buyer:buyerDelete }
    requirements:
          id: \d+

buyer_active:
    pattern: /buyer/active/{id}
    defaults: { _controller: PmsCoreBundle:Buyer:buyerActive }
    requirements:
          id: \d+

buyer_update:
    pattern: /buyer/update/{id}
    defaults: { _controller: PmsCoreBundle:Buyer:buyerUpdate }
    requirements:
          id:  \d+

area_add:
    pattern: /area
    defaults: { _controller: PmsCoreBundle:Area:areaAdd }

area_deleted:
    pattern: /area/deleted
    defaults: { _controller: PmsCoreBundle:Area:areaDeleted }

area_deleted_list:
    pattern: /area/deleted/list
    defaults: { _controller: PmsCoreBundle:Area:areaDeletedList }

area_active:
    pattern: /area/active/{id}
    defaults: { _controller: PmsCoreBundle:Area:areaActive }
    requirements:
          id: \d+

area_list:
    pattern: /area/list
    defaults: { _controller: PmsCoreBundle:Area:areaList }

area_delete:
    pattern: /area/delete/{id}
    defaults: { _controller: PmsCoreBundle:Area:areaDelete }
    requirements:
          id: \d+

area_update:
    pattern: /area/update/{id}
    defaults: { _controller: PmsCoreBundle:Area:areaUpdate }
    requirements:
          id:  \d+

area_check:
    pattern: /area/check
    defaults: { _controller: PmsCoreBundle:Area:areaCheck }
    options:
            expose: true

area_ajax_add:
    pattern: /area/add
    defaults: { _controller: PmsCoreBundle:Area:areaAjaxAdd }
    options:
            expose: true

item_add:
    pattern: /item
    defaults: { _controller: PmsCoreBundle:Item:itemAdd }

item_deleted:
    pattern: /item/deleted
    defaults: { _controller: PmsCoreBundle:Item:itemDeleted }

item_list:
    pattern: /item/list
    defaults: { _controller: PmsCoreBundle:Item:itemList }

item_deleted_list:
    pattern: /item/deleted/list
    defaults: { _controller: PmsCoreBundle:Item:itemDeletedList }

item_delete:
    pattern: /item/delete/{id}
    defaults: { _controller: PmsCoreBundle:Item:itemDelete }
    requirements:
          id: \d+

item_active:
    pattern: /item/active/{id}
    defaults: { _controller: PmsCoreBundle:Item:itemActive }
    requirements:
          id: \d+

item_update:
    pattern: /item/update/{id}
    defaults: { _controller: PmsCoreBundle:Item:itemUpdate }
    requirements:
          id:  \d+

item_check:
    pattern: /item/check
    defaults: { _controller: PmsCoreBundle:Item:itemCheck }
    options:
            expose: true

item_ajax_add:
    pattern: /item/add
    defaults: { _controller: PmsCoreBundle:Item:itemAjaxAdd }
    options:
            expose: true

project_category_add:
    pattern: /project-type
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryAdd }

project_category_deleted:
    pattern: /project-type/category/deleted
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryDeleted }

project_category_deleted_list:
    pattern: /project-type/category/deleted/list
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryDeletedList }

project_category_active:
    pattern: /project-type/category/active/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryActive }
    requirements:
          id: \d+

project_category_list:
    pattern: /project-type/category/list
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryList }

project_category_delete:
    pattern: /project-type/category/delete/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryDelete }
    requirements:
          id: \d+

project_category_update:
    pattern: /project-type/category/update/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryUpdate }
    requirements:
          id:  \d+

project_category_check:
    pattern: /project-type/category/check
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryCheck }
    options:
            expose: true

project_category_ajax_add:
    pattern: /project-type/category/add
    defaults: { _controller: PmsCoreBundle:ProjectCategory:projectCategoryAjaxAdd }
    options:
            expose: true

project_add:
    pattern: /project
    defaults: { _controller: PmsCoreBundle:Project:projectAdd }

project_deleted:
    pattern: /project/deleted
    defaults: { _controller: PmsCoreBundle:Project:projectDeleted }

project_deleted_list:
    pattern: /project/deleted/list
    defaults: { _controller: PmsCoreBundle:Project:projectDeletedList }

project_active:
    pattern: /project/active/{id}
    defaults: { _controller: PmsCoreBundle:Project:projectActive }
    requirements:
          id: \d+

project_list:
    pattern: /project/list
    defaults: { _controller: PmsCoreBundle:Project:projectList }

project_delete:
    pattern: /project/delete/{id}
    defaults: { _controller: PmsCoreBundle:Project:projectDelete }
    requirements:
          id: \d+

project_update:
    pattern: /project/update/{id}
    defaults: { _controller: PmsCoreBundle:Project:projectUpdate }
    requirements:
          id:  \d+

project_check:
    pattern: /project/check
    defaults: { _controller: PmsCoreBundle:Project:projectCheck }
    options:
            expose: true

project_ajax_add:
    pattern: /project/add
    defaults: { _controller: PmsCoreBundle:Project:projectAjaxAdd }
    options:
            expose: true

project_cost_add:
    pattern: /project-cost
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemAdd }

project_cost_list:
    pattern: /cost/list
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemList }

project_cost_details:
    pattern: /project-cost/details/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemDetails }

project_cost_ajax_checked:
    pattern: /project-cost/checked
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemChecked }
    options:
            expose: true

project_cost_delete:
    pattern: /project-cost/delete/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemDelete }
    requirements:
          id:  \d+

project_cost_update:
    pattern: /project-cost/update/{id}
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemUpdate }
    requirements:
          id:  \d+

get_subcategory:
    pattern: /get-subcategory
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:getSubcategoryByCategory }
    options:
        expose: true

project_cost_ajax_add:
    pattern: /project-cost/add
    defaults: { _controller: PmsCoreBundle:ProjectCostItem:projectCostItemAjaxAdd }
    options:
            expose: true

category_check:
    pattern: /category/check
    defaults: { _controller: PmsCoreBundle:Category:categoryCheck }
    options:
            expose: true

category_deleted:
    pattern: /category/deleted
    defaults: { _controller: PmsCoreBundle:Category:categoryDeleted }

category_deleted_list:
    pattern: /category/deleted/list
    defaults: { _controller: PmsCoreBundle:Category:categoryDeletedList }

category_active:
    pattern: /category/active/{id}
    defaults: { _controller: PmsCoreBundle:Category:categoryActive }
    requirements:
          id: \d+

category_add:
    pattern: /category
    defaults: { _controller: PmsCoreBundle:Category:categoryAdd }

category_list:
    pattern: /category/list
    defaults: { _controller: PmsCoreBundle:Category:categoryList }

category_ajax_add:
    pattern: /category/add
    defaults: { _controller: PmsCoreBundle:Category:categoryAjaxAdd }
    options:
            expose: true

category_delete:
    pattern: /category/delete/{id}
    defaults: { _controller: PmsCoreBundle:Category:categoryDelete }
    requirements:
          id: \d+

category_update:
    pattern: /category/update/{id}
    defaults: { _controller: PmsCoreBundle:Category:categoryUpdate }
    requirements:
          id:  \d+

sub_category_check:
    pattern: /sub-category/check
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryCheck }
    options:
            expose: true

sub_category_add:
    pattern: /sub-category
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryAdd }

sub_category_ajax_add:
    pattern: /sub-category/add
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryAjaxAdd }
    options:
        expose: true

sub_category_list:
    pattern: /sub-category/list
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryList }

sub_category_deleted_list:
    pattern: /sub-category/deleted/list
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryDeletedList }

sub_category_delete:
    pattern: /sub-category/delete/{id}
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryDelete }
    requirements:
          id: \d+

sub_category_deleted:
    pattern: /sub-category/deleted
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryDeleted }

sub_category_active:
    pattern: /sub-category/active/{id}
    defaults: { _controller: PmsCoreBundle:SubCategory:subCategoryActive }
    requirements:
          id: \d+

report_project:
    pattern: /report/project
    defaults: { _controller: PmsCoreBundle:Report:projectReport }

report_by_project_details:
    pattern: /report/byProject/details/{id}/{startDate}/{endDate}
    defaults: { _controller: PmsCoreBundle:Report:byProjectDetails }
    requirements:
          id:  \d+

report_by_item_details:
    pattern: /report/byItem/details/{id}/{start}/{end}/{project}
    defaults: { _controller: PmsCoreBundle:Report:byItemDetails }
    requirements:
          id:  \d+

report_item:
    pattern: /report/item
    defaults: { _controller: PmsCoreBundle:Report:itemReport }
    requirements:
          id:  \d+

report_item_details:
    pattern: /report/item/details/{id}/{start}/{end}
    defaults: { _controller: PmsCoreBundle:Report:itemDetails }
    requirements:
          id:  \d+

over_view:
    pattern: /over/view
    defaults: { _controller: PmsCoreBundle:Report:overView }