item_add:
    pattern: /item
    defaults: { _controller: PmsCoreBundle:Core:itemAdd }

item_list:
    pattern: /item/list
    defaults: { _controller: PmsCoreBundle:Core:itemList }

item_delete:
    pattern: /item/delete/{id}
    defaults: { _controller: PmsCoreBundle:Core:itemDelete }
    requirements:
          id: \d+

item_update:
    pattern: /item/update/{id}
    defaults: { _controller: PmsCoreBundle:Core:itemUpdate }
    requirements:
          id:  \d+

project_add:
    pattern: /project
    defaults: { _controller: PmsCoreBundle:Core:projectAdd }

project_list:
    pattern: /project/list
    defaults: { _controller: PmsCoreBundle:Core:projectList }

project_delete:
    pattern: /project/delete/{id}
    defaults: { _controller: PmsCoreBundle:Core:projectDelete }
    requirements:
          id: \d+

project_update:
    pattern: /project/update/{id}
    defaults: { _controller: PmsCoreBundle:Core:projectUpdate }
    requirements:
          id:  \d+

cost_add:
    pattern: /project-cost
    defaults: { _controller: PmsCoreBundle:Core:projectCostAdd }

cost_list:
    pattern: /cost/list
    defaults: { _controller: PmsCoreBundle:Core:projectCostList }

cost_approved:
    pattern: /project-cost/approved/{id}
    defaults: { _controller: PmsCoreBundle:Core:projectCostApproved }
    requirements:
          id: \d+

cost_update:
    pattern: /project-cost/update/{id}
    defaults: { _controller: PmsCoreBundle:Core:projectCostUpdate }
    requirements:
          id:  \d+

item_check:
    pattern: /item/check
    defaults: { _controller: PmsCoreBundle:Core:itemCheck }
    options:
            expose: true

project_check:
    pattern: /project/check
    defaults: { _controller: PmsCoreBundle:Core:projectCheck }
    options:
            expose: true

item_ajax_add:
    pattern: /item/add
    defaults: { _controller: PmsCoreBundle:Core:itemAjaxAdd }
    options:
            expose: true

project_ajax_add:
    pattern: /project/add
    defaults: { _controller: PmsCoreBundle:Core:projectAjaxAdd }
    options:
            expose: true

project_cost_ajax_add:
    pattern: /project-cost/add
    defaults: { _controller: PmsCoreBundle:Core:projectCostAjaxAdd }
    options:
            expose: true

category_add:
    pattern: /category
    defaults: { _controller: PmsCoreBundle:Core:categoryAdd }

category_list:
    pattern: /category/list
    defaults: { _controller: PmsCoreBundle:Core:categoryList }

category_ajax_add:
    pattern: /category/add
    defaults: { _controller: PmsCoreBundle:Core:categoryAjaxAdd }
    options:
            expose: true

category_delete:
    pattern: /category/delete/{id}
    defaults: { _controller: PmsCoreBundle:Core:categoryDelete }
    requirements:
          id: \d+

category_update:
    pattern: /category/update/{id}
    defaults: { _controller: PmsCoreBundle:Core:categoryUpdate }
    requirements:
          id:  \d+

sub_category_add:
    pattern: /sub-category
    defaults: { _controller: PmsCoreBundle:Core:subCategoryAdd }

report_project:
    pattern: /report/project
    defaults: { _controller: PmsCoreBundle:Core:projectReport }

report_project_details:
    pattern: /report/project/details/{id}
    defaults: { _controller: PmsCoreBundle:Core:projectDetails }
    requirements:
          id:  \d+